CREATE PROCEDURE [PLAYER].[SP_GET_TRACK]
	@TYPE INT =1
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @SELECTED_TRACK BIGINT;
	DECLARE @SELECTION INT;
	DECLARE @POWER FLOAT;
	DECLARE @BARRIER FLOAT;
	IF (@TYPE=0)
	BEGIN
		-- Прямой перебор
		DECLARE @TRACK_10_1 BIGINT;
		DECLARE @TRACK_10_2 BIGINT;
		DECLARE @MAX_TRACK_ID BIGINT;
		DECLARE @MIN_TRACK_ID BIGINT;
		DECLARE @FLAG BIT;

		SELECT	@SELECTED_TRACK=[LAST_TRACK_ID], 
				@TRACK_10_1=[TRACK_10_1], 
				@TRACK_10_2=TRACK_10_2,
				@MAX_TRACK_ID=MAX_TRACK_ID,
				@MIN_TRACK_ID=MIN_TRACK_ID,
				@FLAG=FLAG 
			FROM [PLAYER].[T_STATE] WHERE ID=1;
		SELECT [NAME] FROM [PLAYER].T_TRACKS WHERE ID=@SELECTED_TRACK;
		IF ( @SELECTED_TRACK=@MAX_TRACK_ID)
			-- Выбираем одну из 10 сек
				IF (@FLAG=0)
						UPDATE [PLAYER].[T_STATE] SET [LAST_TRACK_ID]=@TRACK_10_1, FLAG=1 WHERE ID=1
				ELSE
						UPDATE [PLAYER].[T_STATE] SET [LAST_TRACK_ID]=@TRACK_10_2, FLAG=0 WHERE ID=1
		ELSE
			IF ((@SELECTED_TRACK=@TRACK_10_1) OR (@SELECTED_TRACK=@TRACK_10_2))
				UPDATE [PLAYER].[T_STATE] SET [LAST_TRACK_ID]=@MIN_TRACK_ID WHERE ID=1
			ELSE
				UPDATE [PLAYER].[T_STATE] SET 
					[LAST_TRACK_ID]=(SELECT MIN(ID) FROM [PLAYER].[T_TRACKS] WHERE ID>@SELECTED_TRACK AND TIME=5) WHERE ID=1
	END
		ELSE IF (@TYPE=1)
	BEGIN
		-- Возвращаем трек
		SELECT @SELECTED_TRACK=[LAST_TRACK_ID], @BARRIER=[BARRIER] FROM [PLAYER].[T_STATE] WHERE ID=1;
		SELECT [NAME] FROM [PLAYER].T_TRACKS WHERE ID=@SELECTED_TRACK;
		-- Определяем какой трек будет играть
		-- Вероятностный метод
		UPDATE [PLAYER].T_TRACK_COUNTER SET [COUNTER]=COUNTER+1 WHERE TRACK_ID=@SELECTED_TRACK;
		SET @POWER=RAND();
		SET @SELECTION=(SELECT MIN(COUNTER) FROM [PLAYER].T_TRACK_COUNTER WHERE TIME=(CASE WHEN (@POWER<=@BARRIER) THEN 5 ELSE 10 END));
		SET @SELECTED_TRACK=(SELECT TOP 1 TRACK_ID FROM [PLAYER].T_TRACK_COUNTER WHERE COUNTER=@SELECTION AND TIME=(CASE WHEN (@POWER<=@BARRIER) THEN 5 ELSE 10 END));
		UPDATE [PLAYER].[T_STATE] SET [LAST_TRACK_ID]=@SELECTED_TRACK;
	END
		ELSE IF (@TYPE=2)
	BEGIN
		-- Случайный выбор
		-- Возвращаем трек
		SELECT [NAME] FROM [PLAYER].T_TRACKS WHERE ID=@SELECTED_TRACK;
		-- Если введено неправильное число		
		SELECT @SELECTED_TRACK=MIN(ID) FROM [PLAYER].[T_TRACKS];
	END
		ELSE
	BEGIN
		-- Возвращаем трек
		SELECT [NAME] FROM [PLAYER].T_TRACKS WHERE ID=@SELECTED_TRACK;
		-- Если введено неправильное число		
		SELECT @SELECTED_TRACK=MIN(ID) FROM [PLAYER].[T_TRACKS];
	END
	-- Записываем информацию об отданном треке
	INSERT INTO [PLAYER].[T_TRACK_LOG](OPERATION_TYPE_ID, TRACK_ID, CONTENT)
		VALUES(4, @SELECTED_TRACK, N'Выбран трек ID'+CAST(@SELECTED_TRACK AS NVARCHAR(12)));
END
